version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: hao_mysql
    restart: always
    environment:
      MYSQL_DATABASE: hao_db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hao_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123456
    depends_on:
      - mysql

volumes:
  mysql_data: